import { supabase } from '@/integrations/supabase/client';
import { useAuthStore } from '@/store/authStore';
import { useAppStore } from '@/store/appStore';
import type { ContentItem, ReviewTaskData, ChatMessage, MetricsCardData } from '@/types/spark';

const DEVICE_ID = 'default';

function getIdentifier() {
  const { user, isAuthenticated } = useAuthStore.getState();
  if (isAuthenticated && user?.id) {
    return { user_id: user.id, device_id: DEVICE_ID };
  }
  return { user_id: null, device_id: DEVICE_ID };
}

export interface ReviewItemRecord {
  item: ContentItem;
  task: ReviewTaskData;
  rejectReason?: string;
}

export interface ReviewHistoryEntry {
  id: string;
  title: string;
  platform: ContentItem['platform'];
  status: ContentItem['status'];
  taskName: string;
  taskSource: ReviewTaskData['source'];
  taskTopic?: string;
  triggeredAt: string;
  updatedAt: string;
  publishedAt?: string;
  publishedPlatforms?: string[];
  rejectReason?: string;
  contentPreview: string;
  /** Full content for detail view */
  content: string;
  cta: string;
  tags: string[];
  coverImage?: string;
}

/** Load all review items as flat history entries (for the Memory page list). */
export async function loadReviewHistory(): Promise<ReviewHistoryEntry[]> {
  const id = getIdentifier();
  const query = supabase
    .from('review_items')
    .select('*')
    .order('updated_at', { ascending: false });

  const { data, error } = id.user_id
    ? await query.eq('user_id', id.user_id)
    : await query.is('user_id', null).eq('device_id', id.device_id);

  if (error) {
    console.error('[review] history load failed:', error);
    return [];
  }
  return (data || []).map(row => ({
    id: row.id,
    title: row.title || '(无标题)',
    platform: row.platform as ContentItem['platform'],
    status: row.status as ContentItem['status'],
    taskName: row.task_name || '审核任务',
    taskSource: (row.task_source as ReviewTaskData['source']) || 'schedule',
    taskTopic: row.task_topic || undefined,
    triggeredAt: row.triggered_at,
    updatedAt: row.updated_at,
    publishedAt: row.published_at || undefined,
    publishedPlatforms: row.published_platforms || [],
    rejectReason: row.reject_reason || undefined,
    contentPreview: (row.content || '').slice(0, 120),
    content: row.content || '',
    cta: row.cta || '',
    tags: row.tags || [],
    coverImage: row.cover_image || undefined,
  }));
}

/**
 * Save a review item to Supabase (insert or update).
 */
export async function saveReviewItem(
  item: ContentItem,
  task: ReviewTaskData,
  rejectReason?: string,
): Promise<void> {
  const id = getIdentifier();
  const { error } = await supabase.from('review_items').upsert(
    {
      id: item.id,
      user_id: id.user_id,
      device_id: id.device_id,
      title: item.title,
      content: item.content,
      platform: item.platform,
      status: item.status,
      tags: item.tags || [],
      cta: item.cta || '',
      cover_image: item.coverImage || null,
      task_name: task.taskName,
      task_source: task.source,
      task_topic: task.topic || null,
      triggered_at: task.triggeredAt,
      reject_reason: rejectReason || null,
      auto_generated: item.autoGenerated ?? true,
    },
    { onConflict: 'id' },
  );
  if (error) console.error('[review] save failed:', error);
}

/**
 * Permanently delete a review item from the database.
 */
export async function deleteReviewItem(id: string): Promise<void> {
  const { error } = await supabase.from('review_items').delete().eq('id', id);
  if (error) console.error('[review] delete failed:', error);
}

/**
 * Update only the status (and optional reject reason) of a persisted review item.
 */
export async function updateReviewItemStatus(
  id: string,
  status: ContentItem['status'],
  rejectReason?: string,
): Promise<void> {
  const patch: { status: ContentItem['status']; reject_reason?: string | null } = { status };
  if (rejectReason !== undefined) patch.reject_reason = rejectReason;
  const { error } = await supabase.from('review_items').update(patch).eq('id', id);
  if (error) console.error('[review] update failed:', error);
}

/**
 * Load all review items for the current user/device, then restore them into
 * the app store as content items + chat messages so the conversation flow
 * shows them after a refresh.
 */
export async function loadReviewItemsIntoStore(): Promise<void> {
  const id = getIdentifier();
  const query = supabase
    .from('review_items')
    .select('*')
    .order('triggered_at', { ascending: true });

  const { data, error } = id.user_id
    ? await query.eq('user_id', id.user_id)
    : await query.is('user_id', null).eq('device_id', id.device_id);

  if (error) {
    console.error('[review] load failed:', error);
    return;
  }
  if (!data || data.length === 0) return;

  const store = useAppStore.getState();
  const existingIds = new Set(store.contents.map(c => c.id));
  const existingMsgIds = new Set(store.messages.map(m => m.id));

  const newContents: ContentItem[] = [];
  const newMessages: ChatMessage[] = [];

  for (const row of data) {
    const item: ContentItem = {
      id: row.id,
      title: row.title,
      content: row.content,
      platform: row.platform as ContentItem['platform'],
      status: row.status as ContentItem['status'],
      tags: row.tags || [],
      cta: row.cta || '',
      coverImage: row.cover_image || undefined,
      createdAt: row.created_at,
      updatedAt: row.updated_at,
      autoGenerated: row.auto_generated,
    };

    if (!existingIds.has(item.id)) newContents.push(item);

    const msgId = `restored-review-${item.id}`;
    if (!existingMsgIds.has(msgId)) {
      const task: ReviewTaskData = {
        source: (row.task_source as ReviewTaskData['source']) || 'schedule',
        taskName: row.task_name || '历史审核任务',
        triggeredAt: row.triggered_at,
        topic: row.task_topic || undefined,
      };

      // Schedule-source reviewing items → simplified reminder pointing to /review
      if (task.source === 'schedule' && item.status === 'reviewing') {
        newMessages.push({
          id: msgId,
          role: 'assistant',
          content: '',
          timestamp: row.triggered_at,
          reviewReminder: {
            taskName: task.taskName,
            message: `定时任务「${task.taskName}」已生成 1 篇内容，请前往审核中心查看`,
            item: { id: item.id, title: item.title, content: item.content, status: item.status },
          },
        });
      } else {
        newMessages.push({
          id: msgId,
          role: 'assistant',
          content: item.status === 'reviewing'
            ? '🟡 这是上次未完成审核的内容，请继续：'
            : item.status === 'approved'
              ? '✅ 这条内容此前已通过审核：'
              : '↻ 这条内容此前已被打回：',
          timestamp: row.triggered_at,
          contentItem: item,
          reviewTask: task,
        });
      }
    }
  }

  if (newContents.length > 0) {
    useAppStore.setState({ contents: [...newContents, ...store.contents] });
  }
  if (newMessages.length > 0) {
    useAppStore.setState({
      messages: [...newMessages, ...useAppStore.getState().messages],
    });
  }
}

/**
 * Load any content_metrics rows that don't yet have a chat message,
 * and inject them as MetricsCard messages into the chat stream.
 * Only loads the aggregated 'all' platform row per item to avoid spam.
 */
export async function loadMetricsIntoStore(): Promise<void> {
  const id = getIdentifier();
  const query = supabase
    .from('content_metrics')
    .select('*')
    .eq('platform', 'all')
    .order('fetched_at', { ascending: true });

  const { data, error } = id.user_id
    ? await query.eq('user_id', id.user_id)
    : await query.is('user_id', null).eq('device_id', id.device_id);

  if (error) {
    console.error('[metrics] load failed:', error);
    return;
  }
  if (!data || data.length === 0) return;

  // Look up titles + published_platforms from review_items
  const reviewIds = [...new Set(data.map(r => r.review_item_id))];
  const { data: items } = await supabase
    .from('review_items')
    .select('id, title, published_platforms, platform')
    .in('id', reviewIds);
  const itemMap = new Map((items || []).map(i => [i.id, i]));

  const store = useAppStore.getState();
  const existingMsgIds = new Set(store.messages.map(m => m.id));
  const newMessages: ChatMessage[] = [];

  for (const row of data) {
    const msgId = `metrics-${row.id}`;
    if (existingMsgIds.has(msgId)) continue;
    const item = itemMap.get(row.review_item_id);
    if (!item) continue;

    const card: MetricsCardData = {
      reviewItemId: row.review_item_id,
      title: item.title || '(无标题)',
      platform: row.platform,
      publishedPlatforms:
        item.published_platforms?.length > 0 ? item.published_platforms : [item.platform],
      fetchedAt: row.fetched_at,
      metrics: {
        views: row.views,
        likes: row.likes,
        comments: row.comments,
        saves: row.saves,
        shares: row.shares,
      },
      aiInsight: row.ai_insight || '',
      source: (row.source as 'mock' | 'real') || 'mock',
    };

    newMessages.push({
      id: msgId,
      role: 'assistant',
      content: `📊 你发布的「${item.title}」24 小时数据回流来啦：`,
      timestamp: row.fetched_at,
      metricsCard: card,
    });
  }

  if (newMessages.length > 0) {
    useAppStore.setState({
      messages: [...useAppStore.getState().messages, ...newMessages],
    });
  }
}

