import { supabase } from '@/integrations/supabase/client';
import { useAuthStore } from '@/store/authStore';
import { useAppStore } from '@/store/appStore';
import type { ContentItem, ReviewTaskData, ChatMessage } from '@/types/spark';

const DEVICE_ID = 'default';

function getIdentifier() {
  const { user, isAuthenticated } = useAuthStore.getState();
  if (isAuthenticated && user?.id) {
    return { user_id: user.id, device_id: DEVICE_ID };
  }
  return { user_id: null, device_id: DEVICE_ID };
}

export interface ReviewItemRecord {
  item: ContentItem;
  task: ReviewTaskData;
  rejectReason?: string;
}

/**
 * Save a review item to Supabase (insert or update).
 */
export async function saveReviewItem(
  item: ContentItem,
  task: ReviewTaskData,
  rejectReason?: string,
): Promise<void> {
  const id = getIdentifier();
  const { error } = await supabase.from('review_items').upsert(
    {
      id: item.id,
      user_id: id.user_id,
      device_id: id.device_id,
      title: item.title,
      content: item.content,
      platform: item.platform,
      status: item.status,
      tags: item.tags || [],
      cta: item.cta || '',
      cover_image: item.coverImage || null,
      task_name: task.taskName,
      task_source: task.source,
      task_topic: task.topic || null,
      triggered_at: task.triggeredAt,
      reject_reason: rejectReason || null,
      auto_generated: item.autoGenerated ?? true,
    },
    { onConflict: 'id' },
  );
  if (error) console.error('[review] save failed:', error);
}

/**
 * Update only the status (and optional reject reason) of a persisted review item.
 */
export async function updateReviewItemStatus(
  id: string,
  status: ContentItem['status'],
  rejectReason?: string,
): Promise<void> {
  const patch: { status: ContentItem['status']; reject_reason?: string | null } = { status };
  if (rejectReason !== undefined) patch.reject_reason = rejectReason;
  const { error } = await supabase.from('review_items').update(patch).eq('id', id);
  if (error) console.error('[review] update failed:', error);
}
  if (rejectReason !== undefined) patch.reject_reason = rejectReason;
  const { error } = await supabase.from('review_items').update(patch).eq('id', id);
  if (error) console.error('[review] update failed:', error);
}

/**
 * Load all review items for the current user/device, then restore them into
 * the app store as content items + chat messages so the conversation flow
 * shows them after a refresh.
 */
export async function loadReviewItemsIntoStore(): Promise<void> {
  const id = getIdentifier();
  const query = supabase
    .from('review_items')
    .select('*')
    .order('triggered_at', { ascending: true });

  const { data, error } = id.user_id
    ? await query.eq('user_id', id.user_id)
    : await query.is('user_id', null).eq('device_id', id.device_id);

  if (error) {
    console.error('[review] load failed:', error);
    return;
  }
  if (!data || data.length === 0) return;

  const store = useAppStore.getState();
  const existingIds = new Set(store.contents.map(c => c.id));
  const existingMsgIds = new Set(store.messages.map(m => m.id));

  const newContents: ContentItem[] = [];
  const newMessages: ChatMessage[] = [];

  for (const row of data) {
    const item: ContentItem = {
      id: row.id,
      title: row.title,
      content: row.content,
      platform: row.platform as ContentItem['platform'],
      status: row.status as ContentItem['status'],
      tags: row.tags || [],
      cta: row.cta || '',
      coverImage: row.cover_image || undefined,
      createdAt: row.created_at,
      updatedAt: row.updated_at,
      autoGenerated: row.auto_generated,
    };

    if (!existingIds.has(item.id)) newContents.push(item);

    const msgId = `restored-review-${item.id}`;
    if (!existingMsgIds.has(msgId)) {
      const task: ReviewTaskData = {
        source: (row.task_source as ReviewTaskData['source']) || 'schedule',
        taskName: row.task_name || '历史审核任务',
        triggeredAt: row.triggered_at,
        topic: row.task_topic || undefined,
      };
      newMessages.push({
        id: msgId,
        role: 'assistant',
        content: item.status === 'reviewing'
          ? '🟡 这是上次未完成审核的内容，请继续：'
          : item.status === 'approved'
            ? '✅ 这条内容此前已通过审核：'
            : '↻ 这条内容此前已被打回：',
        timestamp: row.triggered_at,
        contentItem: item,
        reviewTask: task,
      });
    }
  }

  if (newContents.length > 0) {
    useAppStore.setState({ contents: [...newContents, ...store.contents] });
  }
  if (newMessages.length > 0) {
    useAppStore.setState({
      messages: [...newMessages, ...useAppStore.getState().messages],
    });
  }
}
