export interface QuickAction {
  label: string;
  value: string;
  icon?: string;
  variant?: 'default' | 'primary' | 'outline';
}

export interface OptionCard {
  id: string;
  title: string;
  description?: string;
  image?: string;
  selected?: boolean;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
  suggestions?: string[];
  actions?: QuickAction[];
  options?: OptionCard[];
  image?: string;
}

export type ContentStatus = 'draft' | 'reviewing' | 'approved' | 'published' | 'rejected';
export type Platform = 'xiaohongshu' | 'wechat' | 'douyin';

export interface ContentItem {
  id: string;
  title: string;
  content: string;
  platform: Platform;
  status: ContentStatus;
  coverImage?: string;
  tags?: string[];
  cta?: string;
  createdAt: string;
  updatedAt: string;
  publishedAt?: string;
  metrics?: ContentMetrics;
  autoGenerated?: boolean;
}

export interface ContentMetrics {
  views: number;
  likes: number;
  comments: number;
  shares: number;
  saves?: number;
}

export interface ScheduleConfig {
  enabled: boolean;
  frequency: 'daily' | 'weekly' | 'custom';
  daysOfWeek: number[];
  platforms: Platform[];
  topics: string[];
  style: string;
  postsPerDay: number;
  nextRunAt?: string;
}

export interface BrandMemory {
  name: string;
  industry: string;
  mainBusiness: string;
  targetCustomer: string;
  differentiation: string;
  toneOfVoice: string;
  keywords: string[];
  tabooWords: string[];
  initialized: boolean;
  initStep: number;
  createdAt?: string;
  updatedAt?: string;
}

export interface LearningEntry {
  id: string;
  type: 'edit' | 'feedback' | 'performance' | 'preference';
  category: string;
  insight: string;
  evidence: string;
  confidence: number;
  timestamp: string;
}

export interface Suggestion {
  icon: string;
  text: string;
  desc: string;
}

export type TabId = 'studio' | 'dashboard' | 'schedule' | 'memory' | 'settings';
