export interface QuickAction {
  label: string;
  value: string;
  icon?: string;
  variant?: 'default' | 'primary' | 'outline';
}

export interface OptionCard {
  id: string;
  title: string;
  description?: string;
  image?: string;
  selected?: boolean;
}

export interface ChoiceOption {
  id: string;
  label: string;
  emoji?: string;
}

export interface ReviewTaskData {
  source: 'schedule' | 'auto' | 'manual';
  taskName: string;
  triggeredAt: string;
  topic?: string;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
  suggestions?: string[];
  actions?: QuickAction[];
  options?: OptionCard[];
  choices?: ChoiceOption[];
  image?: string;
  contentItem?: ContentItem;
  reportData?: Record<string, unknown>;
  reviewTask?: ReviewTaskData;
  /** Lightweight reminder pointing to /review (replaces full ReviewCard in chat) */
  reviewReminder?: {
    taskName?: string;
    message?: string;
    item?: Pick<ContentItem, 'id' | 'title' | 'content' | 'status'>;
  };
  distribution?: DistributionData;
  scheduleCard?: ScheduleCardData;
  metricsCard?: MetricsCardData;
  /** When set, renders an error bubble with a retry action */
  error?: {
    message: string;
    /** Original user prompt to retry; if absent, retry button is hidden */
    retryPrompt?: string;
    /** Which handler to invoke on retry */
    retryMode?: 'chat' | 'generate';
  };
}

export interface MetricsCardData {
  reviewItemId: string;
  title: string;
  platform: string; // 'all' | Platform
  publishedPlatforms: string[];
  fetchedAt: string;
  metrics: {
    views: number;
    likes: number;
    comments: number;
    saves: number;
    shares: number;
  };
  aiInsight: string;
  source: 'mock' | 'real';
}

export type ContentStatus = 'draft' | 'reviewing' | 'approved' | 'published' | 'rejected';
export type Platform = 'xiaohongshu' | 'wechat' | 'douyin' | 'tiktok' | 'instagram';

export interface DistributionData {
  contentId: string;
  title: string;
  defaultPlatforms?: Platform[];
  /** Platforms it has been published to (sets card to success state on restore) */
  publishedPlatforms?: Platform[];
}

export interface ScheduleCardData {
  /** ID for tracking the proposed plan */
  id: string;
  /** Suggested topic parsed from user message */
  suggestedTopic?: string;
  /** Suggested frequency parsed from user message */
  suggestedFrequency?: 'daily' | 'weekly';
  /** Whether the plan was already confirmed (for restore) */
  confirmed?: boolean;
}

export interface ContentVersion {
  id: string;
  title: string;
  content: string;
  cta?: string;
  tags?: string[];
  coverImage?: string;
  savedAt: string;
  label?: string;
}

export interface ContentItem {
  id: string;
  title: string;
  content: string;
  platform: Platform;
  status: ContentStatus;
  coverImage?: string;
  tags?: string[];
  cta?: string;
  createdAt: string;
  updatedAt: string;
  publishedAt?: string;
  metrics?: ContentMetrics;
  autoGenerated?: boolean;
  versions?: ContentVersion[];
}

export interface ContentMetrics {
  views: number;
  likes: number;
  comments: number;
  shares: number;
  saves?: number;
}

export interface ScheduleConfig {
  enabled: boolean;
  frequency: 'daily' | 'weekly' | 'custom';
  daysOfWeek: number[];
  platforms: Platform[];
  topics: string[];
  style: string;
  postsPerDay: number;
  scheduledTimes: string[];
  nextRunAt?: string;
}

export interface BrandMemory {
  name: string;
  industry: string;
  mainBusiness: string;
  targetCustomer: string;
  differentiation: string;
  toneOfVoice: string;
  keywords: string[];
  tabooWords: string[];
  initialized: boolean;
  initStep: number;
  createdAt?: string;
  updatedAt?: string;
}

export interface LearningEntry {
  id: string;
  type: 'edit' | 'feedback' | 'performance' | 'preference';
  category: string;
  insight: string;
  evidence: string;
  confidence: number;
  timestamp: string;
}

export interface Suggestion {
  icon: string;
  text: string;
  desc: string;
}

export type TabId = 'studio' | 'dashboard' | 'schedule' | 'review' | 'memory';
