import { useState, useRef, useEffect, useCallback } from 'react';
import { useAppStore } from '../store/appStore';
import type { ContentItem, Platform } from '../types/spark';
import {
  Sparkles,
  Plus,
  Bot,
  ChevronDown,
  Send,
  CheckCircle,
  Wand2,
  Maximize2,
  Minimize2,
  FileText,
} from 'lucide-react';
import { toast } from 'sonner';

// --- Inline AI Toolbar ---
function AIFloatingToolbar({
  position,
  onAction,
}: {
  position: { top: number; left: number };
  onAction: (action: string) => void;
}) {
  const actions = [
    { id: 'rewrite', label: 'AI 改写', icon: <Wand2 size={12} /> },
    { id: 'expand', label: '扩写', icon: <Maximize2 size={12} /> },
    { id: 'simplify', label: '精简', icon: <Minimize2 size={12} /> },
  ];

  return (
    <div
      className="fixed z-50 flex items-center gap-1 bg-spark-surface border border-spark-gray-200 rounded-lg shadow-lg px-1.5 py-1"
      style={{
        top: position.top - 44,
        left: position.left,
        animation: 'spark-fade-in 0.15s ease',
      }}
    >
      <Sparkles size={12} className="text-spark-orange mr-1" />
      {actions.map((a) => (
        <button
          key={a.id}
          onClick={() => onAction(a.id)}
          className="flex items-center gap-1 px-2.5 py-1 rounded-md text-xs font-medium text-spark-gray-600 hover:bg-spark-warm hover:text-spark-orange transition-colors"
        >
          {a.icon}
          {a.label}
        </button>
      ))}
    </div>
  );
}

// --- Draft Dropdown ---
function DraftDropdown({
  open,
  onClose,
  contents,
  selectedId,
  onSelect,
  onCreate,
}: {
  open: boolean;
  onClose: () => void;
  contents: ContentItem[];
  selectedId: string | null;
  onSelect: (id: string) => void;
  onCreate: () => void;
}) {
  if (!open) return null;
  return (
    <>
      <div className="fixed inset-0 z-30" onClick={onClose} />
      <div className="absolute top-full left-0 mt-1 w-72 bg-spark-surface border border-spark-gray-200 rounded-xl shadow-xl z-40 overflow-hidden" style={{ animation: 'spark-fade-in 0.15s ease' }}>
        <div className="p-2 border-b border-spark-gray-100 flex items-center justify-between">
          <span className="text-xs font-semibold text-spark-gray-500">草稿列表</span>
          <button
            onClick={onCreate}
            className="w-6 h-6 rounded-md bg-spark-warm text-spark-orange flex items-center justify-center hover:bg-spark-orange hover:text-primary-foreground transition-colors"
          >
            <Plus size={14} />
          </button>
        </div>
        <div className="max-h-64 overflow-y-auto p-1.5 space-y-0.5">
          {contents.length === 0 && (
            <div className="text-center py-4 text-spark-gray-400 text-xs">暂无草稿</div>
          )}
          {contents.map((item) => (
            <button
              key={item.id}
              onClick={() => { onSelect(item.id); onClose(); }}
              className={`w-full text-left p-2 rounded-lg transition-colors text-sm ${
                selectedId === item.id
                  ? 'bg-spark-warm text-spark-orange'
                  : 'hover:bg-spark-gray-100 text-spark-gray-600'
              }`}
            >
              <div className="font-medium truncate flex items-center gap-1">
                {item.autoGenerated && <Bot size={11} className="text-spark-orange shrink-0" />}
                {item.title || '未命名草稿'}
              </div>
              <div className="text-[10px] text-spark-gray-400 mt-0.5">
                {item.platform === 'xiaohongshu' ? '小红书' : item.platform === 'wechat' ? '公众号' : '抖音'}
                {' · '}
                {item.status === 'published' ? '已发布' : '草稿'}
              </div>
            </button>
          ))}
        </div>
      </div>
    </>
  );
}

// --- Main Editor Canvas ---
export default function EditorCanvas() {
  const { contents, setContents, selectedContentId, setSelectedContentId } = useAppStore();
  const [draftsOpen, setDraftsOpen] = useState(false);
  const [toolbarPos, setToolbarPos] = useState<{ top: number; left: number } | null>(null);
  const [selectedText, setSelectedText] = useState('');
  const editorRef = useRef<HTMLDivElement>(null);

  const selectedContent = contents.find((c) => c.id === selectedContentId);

  const updateContent = (updates: Partial<ContentItem>) => {
    if (!selectedContent) return;
    const updated: ContentItem = {
      ...selectedContent,
      ...updates,
      updatedAt: new Date().toISOString(),
    };
    setContents(contents.map((c) => (c.id === updated.id ? updated : c)));
  };

  const createNew = () => {
    const newItem: ContentItem = {
      id: Date.now().toString(),
      title: '',
      content: '',
      platform: 'xiaohongshu',
      status: 'draft',
      tags: [],
      cta: '',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    setContents([newItem, ...contents]);
    setSelectedContentId(newItem.id);
    setDraftsOpen(false);
  };

  const handlePublish = () => {
    if (!selectedContent) return;
    updateContent({
      status: 'published',
      publishedAt: new Date().toISOString(),
    });
    toast.success('内容已发布！');
  };

  // Text selection detection for AI floating toolbar
  const handleMouseUp = useCallback(() => {
    const selection = window.getSelection();
    if (!selection || selection.isCollapsed || !selection.toString().trim()) {
      // Delay hiding to allow button clicks
      setTimeout(() => setToolbarPos(null), 150);
      return;
    }
    const text = selection.toString().trim();
    if (text.length < 2) return;

    const range = selection.getRangeAt(0);
    const rect = range.getBoundingClientRect();
    setSelectedText(text);
    setToolbarPos({
      top: rect.top + window.scrollY,
      left: rect.left + rect.width / 2 - 120,
    });
  }, []);

  const handleToolbarAction = (action: string) => {
    if (!selectedText || !selectedContent) return;
    const actionLabels: Record<string, string> = {
      rewrite: 'AI 改写',
      expand: '扩写',
      simplify: '精简',
    };
    toast.info(`正在${actionLabels[action] || action}选中文本...`);
    setToolbarPos(null);
    // The actual AI call would go through the command panel
  };

  // Platform labels
  const platformLabel = (p: Platform) =>
    p === 'xiaohongshu' ? '小红书' : p === 'wechat' ? '公众号' : '抖音';

  return (
    <div className="flex-1 flex flex-col min-w-0 h-screen bg-spark-gray-50">
      {/* Top Bar */}
      <div className="h-12 border-b border-spark-gray-200 bg-spark-surface flex items-center px-4 gap-3 shrink-0">
        {/* Draft selector */}
        <div className="relative">
          <button
            onClick={() => setDraftsOpen(!draftsOpen)}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg hover:bg-spark-gray-100 transition-colors text-sm"
          >
            <FileText size={14} className="text-spark-gray-400" />
            <span className="font-medium text-spark-gray-700 max-w-[180px] truncate">
              {selectedContent?.title || '未命名草稿'}
            </span>
            <ChevronDown size={14} className="text-spark-gray-400" />
          </button>
          <DraftDropdown
            open={draftsOpen}
            onClose={() => setDraftsOpen(false)}
            contents={contents}
            selectedId={selectedContentId}
            onSelect={setSelectedContentId}
            onCreate={createNew}
          />
        </div>

        {selectedContent && (
          <>
            {/* AI badge */}
            {selectedContent.autoGenerated && (
              <span className="inline-flex items-center gap-1 bg-spark-orange/10 text-spark-orange text-[11px] font-medium px-2 py-0.5 rounded-full">
                <Bot size={11} /> AI 生成
              </span>
            )}

            {/* Platform */}
            <select
              value={selectedContent.platform}
              onChange={(e) => updateContent({ platform: e.target.value as Platform })}
              className="spark-input w-auto h-8 text-xs"
            >
              <option value="xiaohongshu">小红书</option>
              <option value="wechat">公众号</option>
              <option value="douyin">抖音</option>
            </select>

            <div className="flex-1" />

            {/* Publish */}
            {selectedContent.status === 'published' ? (
              <span className="inline-flex items-center gap-1 text-xs font-medium" style={{ color: 'oklch(0.6 0.15 145)' }}>
                <CheckCircle size={14} /> 已发布
              </span>
            ) : (
              <button onClick={handlePublish} className="spark-btn-primary text-xs py-1.5 px-4">
                <Send size={13} /> 发布
              </button>
            )}
          </>
        )}

        {!selectedContent && (
          <button onClick={createNew} className="spark-btn-primary text-xs py-1.5 px-4 ml-auto">
            <Plus size={13} /> 新建草稿
          </button>
        )}
      </div>

      {/* Canvas */}
      {selectedContent ? (
        <div className="flex-1 overflow-y-auto p-6 md:p-10" onMouseUp={handleMouseUp}>
          <div
            ref={editorRef}
            className="max-w-2xl mx-auto bg-spark-surface rounded-2xl border border-spark-gray-200 shadow-sm p-8 min-h-[60vh]"
          >
            {/* Title */}
            <input
              value={selectedContent.title}
              onChange={(e) => updateContent({ title: e.target.value })}
              placeholder="输入标题..."
              className="w-full text-2xl font-bold text-spark-gray-800 bg-transparent border-none outline-none placeholder:text-spark-gray-300 mb-4"
            />

            {/* Divider */}
            <div className="h-px bg-spark-gray-100 mb-4" />

            {/* Body */}
            <textarea
              value={selectedContent.content}
              onChange={(e) => updateContent({ content: e.target.value })}
              placeholder="开始写作，或让 AI 指挥舱帮你生成内容..."
              className="w-full min-h-[40vh] text-[15px] leading-relaxed text-spark-gray-700 bg-transparent border-none outline-none resize-none placeholder:text-spark-gray-300"
            />

            {/* Tags & CTA */}
            <div className="mt-6 pt-4 border-t border-spark-gray-100 space-y-3">
              {/* CTA */}
              <div className="flex items-center gap-2">
                <span className="text-[11px] font-medium text-spark-gray-400 w-10 shrink-0">CTA</span>
                <input
                  value={selectedContent.cta || ''}
                  onChange={(e) => updateContent({ cta: e.target.value })}
                  placeholder="行动号召..."
                  className="flex-1 text-sm text-spark-gray-600 bg-transparent border-none outline-none placeholder:text-spark-gray-300"
                />
              </div>
              {/* Tags */}
              <div className="flex items-center gap-2 flex-wrap">
                <span className="text-[11px] font-medium text-spark-gray-400 w-10 shrink-0">标签</span>
                {(selectedContent.tags || []).map((t) => (
                  <span
                    key={t}
                    className="inline-flex items-center gap-1 bg-spark-warm text-spark-orange text-xs px-2 py-0.5 rounded-full"
                  >
                    #{t}
                    <button
                      onClick={() =>
                        updateContent({ tags: (selectedContent.tags || []).filter((x) => x !== t) })
                      }
                      className="hover:text-destructive"
                    >
                      ×
                    </button>
                  </span>
                ))}
                <input
                  placeholder="添加标签..."
                  className="text-xs text-spark-gray-500 bg-transparent border-none outline-none w-24"
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') {
                      e.preventDefault();
                      const val = (e.target as HTMLInputElement).value.trim();
                      if (val && !(selectedContent.tags || []).includes(val)) {
                        updateContent({ tags: [...(selectedContent.tags || []), val] });
                      }
                      (e.target as HTMLInputElement).value = '';
                    }
                  }}
                />
              </div>
            </div>
          </div>

          {/* Floating AI toolbar */}
          {toolbarPos && (
            <AIFloatingToolbar position={toolbarPos} onAction={handleToolbarAction} />
          )}
        </div>
      ) : (
        <div className="flex-1 flex items-center justify-center">
          <div className="text-center">
            <div className="w-16 h-16 rounded-2xl bg-spark-warm flex items-center justify-center mx-auto mb-4">
              <Sparkles size={28} className="text-spark-orange" />
            </div>
            <h3 className="text-lg font-semibold text-spark-gray-700 mb-1">开始创作</h3>
            <p className="text-sm text-spark-gray-400 mb-4">
              在左侧 AI 指挥舱输入指令，或新建一篇草稿
            </p>
            <button onClick={createNew} className="spark-btn-primary text-sm">
              <Plus size={16} /> 新建草稿
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
