import { useState } from 'react';
import { Clock, AlertCircle, CheckCircle2, RotateCcw, Loader2, X, Sparkles, Briefcase, Scissors } from 'lucide-react';
import { useAppStore } from '../store/appStore';
import type { ContentItem, ReviewTaskData, ChatMessage } from '../types/spark';
import { streamChat } from '../lib/ai-stream';
import { loadUserPrefs } from '../lib/user-prefs';
import { saveReviewItem, updateReviewItemStatus } from '../lib/review-persistence';
import ContentCard from './ContentCard';
import { toast } from 'sonner';

interface ReviewCardProps {
  item: ContentItem;
  task?: ReviewTaskData;
}

export default function ReviewCard({ item: itemProp, task }: ReviewCardProps) {
  const { contents, setContents, addMessage } = useAppStore();
  const item = contents.find(c => c.id === itemProp.id) || itemProp;
  const [rejecting, setRejecting] = useState(false);
  const [rejectReason, setRejectReason] = useState('');
  const [regenerating, setRegenerating] = useState(false);

  const isReviewing = item.status === 'reviewing' || item.status === 'draft';
  const isApproved = item.status === 'approved' || item.status === 'published';
  const isRejected = item.status === 'rejected';

  const headerLabel = task?.taskName || '定时任务生成的内容';

  const updateStatus = (next: ContentItem['status'], extra: Partial<ContentItem> = {}) => {
    const updated = contents.map(c =>
      c.id === item.id
        ? { ...c, status: next, updatedAt: new Date().toISOString(), ...extra }
        : c
    );
    setContents(updated);
  };

  const appendUserMessage = (content: string) => {
    const msg: ChatMessage = {
      id: `${Date.now()}-user-review`,
      role: 'user',
      content,
      timestamp: new Date().toISOString(),
    };
    addMessage(msg);
  };

  const handleApprove = () => {
    updateStatus('approved');
    updateReviewItemStatus(item.id, 'approved');
    appendUserMessage(`[已通过] 这篇「${item.title}」可以发布`);
    addMessage({
      id: `${Date.now()}-approved-dist`,
      role: 'assistant',
      content: `太好了！「${item.title}」已通过审核 ✅，请选择要分发的平台：`,
      timestamp: new Date().toISOString(),
      distribution: {
        contentId: item.id,
        title: item.title,
        defaultPlatforms: [item.platform],
      },
    });
    toast.success('内容已通过审核');
  };

  const runRegenerate = async (reason: string, presetLabel?: string) => {
    if (!reason.trim()) {
      toast.error('请填写打回意见');
      return;
    }

    updateStatus('rejected');
    updateReviewItemStatus(item.id, 'rejected', reason);
    appendUserMessage(presetLabel ? `[快速微调] ${presetLabel}` : `[已打回] 修改要求：${reason}`);
    setRejecting(false);

    setRegenerating(true);
    addMessage({
      id: `${Date.now()}-regen-status`,
      role: 'assistant',
      content: '收到反馈，正在为你重新创作...',
      timestamp: new Date().toISOString(),
    });

    const userPrefs = loadUserPrefs();
    let raw = '';
    const newId = `${Date.now()}-regen`;

    await streamChat({
      messages: [{
        role: 'user',
        content: `请基于以下原文和修改意见重新生成一篇文章。\n\n原标题：${item.title}\n原内容：${item.content}\n\n修改意见：${reason}\n\n写作风格：${userPrefs.writingStyle}，语气：${userPrefs.writingTone}`,
      }],
      mode: 'generate',
      platform: item.platform,
      onDelta: (chunk) => { raw += chunk; },
      onDone: () => {
        let parsed: { title: string; content: string; cta: string; tags: string[] };
        try {
          let cleaned = raw.trim();
          if (cleaned.startsWith('```')) {
            cleaned = cleaned.replace(/^```(?:json)?\s*/, '').replace(/\s*```$/, '');
          }
          parsed = JSON.parse(cleaned);
        } catch {
          parsed = { title: item.title, content: raw, cta: item.cta || '', tags: item.tags || [] };
        }

        const newItem: ContentItem = {
          id: newId,
          title: parsed.title || item.title,
          content: parsed.content || raw,
          platform: item.platform,
          status: 'reviewing',
          tags: Array.isArray(parsed.tags) ? parsed.tags : [],
          cta: parsed.cta || '',
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          autoGenerated: true,
        };

        const current = useAppStore.getState().contents;
        setContents([newItem, ...current]);

        const newTask = {
          source: 'auto' as const,
          taskName: `${headerLabel}（重写版）`,
          triggeredAt: new Date().toISOString(),
          topic: task?.topic,
        };

        addMessage({
          id: `${Date.now()}-regen-card`,
          role: 'assistant',
          content: '✏️ 根据你的反馈，我重新写了一版，请审核：',
          timestamp: new Date().toISOString(),
          contentItem: newItem,
          reviewTask: newTask,
        });

        // Persist new version to Supabase
        saveReviewItem(newItem, newTask);

        setRegenerating(false);
        setRejectReason('');
        toast.success('已生成新版本，请再次审核');
      },
      onError: (err) => {
        addMessage({
          id: `${Date.now()}-regen-err`,
          role: 'assistant',
          content: `⚠️ 重新生成失败：${err}`,
          timestamp: new Date().toISOString(),
        });
        setRegenerating(false);
      },
    });
  };

  return (
    <div className="rounded-xl border border-yellow-300/60 bg-yellow-50/50 overflow-hidden">
      {/* Header */}
      <div className="flex items-center gap-2 px-4 py-2.5 bg-yellow-100/60 border-b border-yellow-200/60">
        <div className="flex items-center gap-1.5">
          <Clock size={14} className="text-yellow-700" />
          <AlertCircle size={14} className="text-yellow-700" />
        </div>
        <div className="flex-1 min-w-0">
          <div className="text-[12px] font-semibold text-yellow-800 leading-tight">
            🟡 待审核：{headerLabel}
          </div>
          <div className="text-[11px] text-yellow-700/70 mt-0.5">
            AI 已生成内容，等待你确认
          </div>
        </div>
        {isApproved && (
          <span className="text-[11px] px-2 py-0.5 rounded-full bg-green-100 text-green-700">已通过</span>
        )}
        {isRejected && (
          <span className="text-[11px] px-2 py-0.5 rounded-full bg-red-100 text-red-700">已打回</span>
        )}
      </div>

      {/* Content */}
      <div className="p-3 bg-white">
        <ContentCard item={item} />
      </div>

      {/* Quick-tune presets */}
      {isReviewing && !rejecting && !regenerating && (
        <div className="px-4 pt-3 pb-1 bg-yellow-50/30 border-t border-yellow-200/40">
          <div className="text-[11px] text-[#999] mb-1.5">⚡ 快速微调（一键重写）</div>
          <div className="flex flex-wrap gap-1.5">
            {[
              { label: '语气更活泼', icon: <Sparkles size={11} />, prompt: '把语气改得更活泼、轻松、有感染力，多用口语化表达和有趣的比喻，让读者读起来有亲切感。' },
              { label: '语气更专业', icon: <Briefcase size={11} />, prompt: '把语气改得更专业、严谨、权威，使用行业术语和数据支撑观点，去掉过于口语化的表达。' },
              { label: '更精简', icon: <Scissors size={11} />, prompt: '在保留核心信息和关键卖点的前提下，把内容精简到原文的 60% 长度左右，去除冗余表达。' },
            ].map(preset => (
              <button
                key={preset.label}
                onClick={() => runRegenerate(preset.prompt, preset.label)}
                className="flex items-center gap-1 px-2.5 py-1 rounded-full text-[12px] bg-white border border-yellow-200 text-[#666] hover:bg-yellow-50 hover:border-yellow-400 hover:text-spark-orange transition-colors"
              >
                {preset.icon}
                {preset.label}
              </button>
            ))}
          </div>
        </div>
      )}

      {/* Actions */}
      {isReviewing && !rejecting && (
        <div className="flex items-center gap-2 px-4 py-3 bg-yellow-50/30">
          <button
            onClick={handleApprove}
            disabled={regenerating}
            className="flex-1 flex items-center justify-center gap-1.5 py-2 rounded-lg bg-green-600 text-white text-[13px] font-medium hover:bg-green-700 transition-colors disabled:opacity-50"
          >
            {regenerating ? <Loader2 size={14} className="animate-spin" /> : <CheckCircle2 size={14} />}
            {regenerating ? '重新生成中...' : '通过并分发'}
          </button>
          <button
            onClick={() => setRejecting(true)}
            disabled={regenerating}
            className="flex-1 flex items-center justify-center gap-1.5 py-2 rounded-lg bg-red-50 text-red-600 border border-red-200 text-[13px] font-medium hover:bg-red-100 transition-colors disabled:opacity-50"
          >
            <RotateCcw size={14} />
            自定义打回
          </button>
        </div>
      )}

      {isReviewing && rejecting && (
        <div className="px-4 py-3 bg-yellow-50/30 border-t border-yellow-200/40 space-y-2">
          <div className="flex items-center justify-between">
            <span className="text-[12px] font-medium text-[#666]">告诉我哪里需要修改：</span>
            <button
              onClick={() => { setRejecting(false); setRejectReason(''); }}
              className="text-[#999] hover:text-[#666]"
            >
              <X size={14} />
            </button>
          </div>
          <textarea
            value={rejectReason}
            onChange={(e) => setRejectReason(e.target.value)}
            placeholder="例如：语气太严肃了，活泼一点；或者：开头不够吸引人..."
            rows={2}
            className="w-full text-[13px] text-[#333] bg-white border border-yellow-200 rounded-lg px-3 py-2 outline-none focus:border-yellow-400 resize-none"
          />
          <button
            onClick={() => runRegenerate(rejectReason)}
            disabled={regenerating || !rejectReason.trim()}
            className="w-full flex items-center justify-center gap-1.5 py-2 rounded-lg bg-spark-orange text-white text-[13px] font-medium hover:opacity-90 transition-opacity disabled:opacity-50"
          >
            {regenerating ? <Loader2 size={14} className="animate-spin" /> : <RotateCcw size={14} />}
            {regenerating ? '重新生成中...' : '提交并重写'}
          </button>
        </div>
      )}
    </div>
  );
}
