// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseAdminClient() {
  // Worker SSR sometimes doesn't expose runtime secrets via process.env;
  // fall back to the build-time VITE_* URL which is always inlined.
  const SUPABASE_URL =
    process.env.SUPABASE_URL || import.meta.env.VITE_SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const isDev = import.meta.env.DEV;
    const missing = [
      !SUPABASE_URL && 'SUPABASE_URL',
      !SUPABASE_SERVICE_ROLE_KEY && 'SUPABASE_SERVICE_ROLE_KEY',
    ].filter(Boolean).join(', ');

    const message = isDev
      ? `[本地开发] 缺少后端密钥：${missing}\n` +
        `\n` +
        `此功能需要服务端密钥才能运行（仅线上环境自动注入）。\n` +
        `解决方法二选一：\n` +
        `  1. 直接在 Preview URL 上测试（推荐，云端密钥已配好）\n` +
        `  2. 本地跑通：在项目根目录创建 .env.local，填入：\n` +
        `     SUPABASE_URL=https://<your-project>.supabase.co\n` +
        `     SUPABASE_SERVICE_ROLE_KEY=<从 Cloud → Secrets 复制>\n`
      : `Server misconfiguration: missing ${missing}. Please contact support.`;

    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
